version: "3.8"
services:
  web:
    build:
      context: ./front-next
      target: runner
    volumes:
      - ./front-next:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    user: root
